In [1]:
import numpy as np

In [2]:
one = np.array([1, 8, 9])

In [3]:
one

array([1, 8, 9])

In [4]:
one.ndim

1

In [5]:
two = np.array([[1, 2, 3]])

In [6]:
two.ndim

2

In [7]:
five = np.array([[[[[1, 2, 3, 4, 5]]]]])

In [8]:
five.ndim

5

In [9]:
two.shape

(1, 3)

In [10]:
two.size

3

In [11]:
two.dtype

dtype('int32')

In [12]:
two.itemsize

4

In [13]:
one_arr = np.ones((3,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
zero_arr = np.zeros((3,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
random = np.random.random((3,3))
random

array([[0.66568525, 0.66751239, 0.82236303],
       [0.64139812, 0.54597785, 0.64445593],
       [0.33849141, 0.16939369, 0.73052509]])

In [16]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arrange = np.arange(5, 11)
arrange

array([ 5,  6,  7,  8,  9, 10])

In [18]:
linspace = np.linspace(2, 10, 2)
linspace

array([ 2., 10.])

In [19]:
linspace1 = np.linspace(2, 10, 20)
linspace1

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [20]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [21]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
my_tuple = {1, 2, 3, 4, 5, 6}
my_arr = np.array(my_tuple)
my_arr

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [23]:
# array = [0, 1, 2, 3, 4, 5]
arr[::2]

array([0, 2, 4])

In [24]:
arr[::-1]

array([5, 4, 3, 2, 1, 0])

In [25]:
kernel = np.array([[1, 2, 3],[5, 6, 7]])
kernel

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
kernel.flatten()

array([1, 2, 3, 5, 6, 7])

In [27]:
array1 = np.array([[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]])
array1

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]])

In [28]:
array1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
kernel.size

6

In [30]:
print(kernel.resize(3,2))

None


In [31]:
my_arr = np.array([[0,1],[2,3]])
my_arr

array([[0, 1],
       [2, 3]])

In [32]:
my_arr = np.resize(1,6)
my_arr

array([1, 1, 1, 1, 1, 1])

In [33]:
np.resize(my_arr,(2,3))

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
import pandas as pd

In [35]:
my_dict = {"Name" : ["Siddesh" , "Sahil", "Shreyash", "Vedant"],
           "Roll.no" : ["39010", "39019", "39014", "39007"],
           "Age" : ["20", "21", "20", "22"],
           "Attendance" : ["100", "96", "93", "90"]
          }
my_dict

{'Name': ['Siddesh', 'Sahil', 'Shreyash', 'Vedant'],
 'Roll.no': ['39010', '39019', '39014', '39007'],
 'Age': ['20', '21', '20', '22'],
 'Attendance': ['100', '96', '93', '90']}

In [36]:
df = pd.DataFrame(my_dict)
df

Name Roll.no Age Attendance
0   Siddesh   39010  20        100
1     Sahil   39019  21         96
2  Shreyash   39014  20         93
3    Vedant   39007  22         90

In [37]:
df.describe

<bound method NDFrame.describe of        Name Roll.no Age Attendance
0   Siddesh   39010  20        100
1     Sahil   39019  21         96
2  Shreyash   39014  20         93
3    Vedant   39007  22         90>

In [38]:
df.describe()

Name Roll.no Age Attendance
count         4       4   4          4
unique        4       4   3          4
top     Siddesh   39010  20        100
freq          1       1   2          1

In [39]:
import numpy as np
import pandas as pd

In [40]:
data = {
    "Energy Source": ["Solar" , "Wind" , "Hydropower" , "Geothermal" , "Biomass" , "Nuclear"],
    "Energy Consumption":[1200 , np.nan , 2900 , np.nan , 2500 , 3200],
    "Cost Millions ":[200 , 400 , np.nan , 150 , 250 , np.nan]
}

In [41]:
energy_df = pd.DataFrame(data)
energy_df

Energy Source  Energy Consumption  Cost Millions 
0         Solar              1200.0           200.0
1          Wind                 NaN           400.0
2    Hydropower              2900.0             NaN
3    Geothermal                 NaN           150.0
4       Biomass              2500.0           250.0
5       Nuclear              3200.0             NaN

In [42]:
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Energy Source       6 non-null      object 
 1   Energy Consumption  4 non-null      float64
 2   Cost Millions       4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 276.0+ bytes


In [43]:
energy_df.isna().sum()

Energy Source         0
Energy Consumption    2
Cost Millions         2
dtype: int64

In [44]:
energy_df.describe()

Energy Consumption  Cost Millions 
count            4.000000        4.000000
mean          2450.000000      250.000000
std            881.286938      108.012345
min           1200.000000      150.000000
25%           2175.000000      187.500000
50%           2700.000000      225.000000
75%           2975.000000      287.500000
max           3200.000000      400.000000

In [45]:
import seaborn as sea

In [46]:
#cleaned_df = energy_df.dropna()

In [47]:
#cleaned_df

In [48]:
sea.boxplot(energy_df)

<Axes: >

In [49]:
energy_df.columns

Index(['Energy Source', 'Energy Consumption', 'Cost Millions '], dtype='object')

In [50]:
energy_df['Energy Consumption'].fillna(energy_df['Energy Consumption'].mean(), inplace = True)

In [51]:
energy_df

Energy Source  Energy Consumption  Cost Millions 
0         Solar              1200.0           200.0
1          Wind              2450.0           400.0
2    Hydropower              2900.0             NaN
3    Geothermal              2450.0           150.0
4       Biomass              2500.0           250.0
5       Nuclear              3200.0             NaN

In [52]:
energy_df["Cost Millions "].fillna(energy_df["Cost Millions "].mean(), inplace = True )

energy_df

Energy Source  Energy Consumption  Cost Millions 
0         Solar              1200.0           200.0
1          Wind              2450.0           400.0
2    Hydropower              2900.0           250.0
3    Geothermal              2450.0           150.0
4       Biomass              2500.0           250.0
5       Nuclear              3200.0           250.0

In [53]:
energy_df.isnull().sum()

Energy Source         0
Energy Consumption    0
Cost Millions         0
dtype: int64

In [54]:
import warnings

warnings.filterwarnings("ignore")

In [55]:
energy_df["Cost Millions "].fillna(energy_df["Cost Millions "].mean(), inplace = True )

energy_df1 = energy_df # For second transformation(Standard Transformation)
energy_df

Energy Source  Energy Consumption  Cost Millions 
0         Solar              1200.0           200.0
1          Wind              2450.0           400.0
2    Hydropower              2900.0           250.0
3    Geothermal              2450.0           150.0
4       Biomass              2500.0           250.0
5       Nuclear              3200.0           250.0

In [56]:
from sklearn.preprocessing import MinMaxScaler

In [57]:
energy_df.columns

Index(['Energy Source', 'Energy Consumption', 'Cost Millions '], dtype='object')

In [58]:
scaler = MinMaxScaler()

In [59]:
energy_df[["Energy Consumption", "Cost Millions "]] = scaler.fit_transform(energy_df[["Energy Consumption", "Cost Millions " ]])

In [ ]:
energy_df

In [61]:
from sklearn.preprocessing import StandardScaler

In [62]:
new_scaler = StandardScaler()

In [63]:
energy_df1[["Energy Consumption", "Cost Millions "]] = new_scaler.fit_transform(energy_df1[["Energy Consumption", "Cost Millions " ]])

In [64]:
energy_df1

Energy Source  Energy Consumption  Cost Millions 
0         Solar       -2.005893e+00   -6.546537e-01
1          Wind        3.563181e-16    1.963961e+00
2    Hydropower        7.221213e-01    1.817029e-16
3    Geothermal        3.563181e-16   -1.309307e+00
4       Biomass        8.023570e-02    1.817029e-16
5       Nuclear        1.203536e+00    1.817029e-16